-- Identity change controls and verified-name review workflow.
-- Display name: unverified members may change twice per rolling 14 days.
-- Verified members must submit a review request.
-- Username: all members may change once per rolling 30 days.

begin;

alter table public.social_profiles
  add column if not exists is_verified boolean not null default false;

comment on column public.social_profiles.is_verified is
  'Server-owned SautiLink social verification state. Members cannot self-assign verification.';

revoke update (is_verified) on table public.social_profiles from authenticated;
grant select (is_verified) on table public.social_profiles to anon, authenticated;

-- Full name becomes controlled by the identity RPC so the account and social
-- profile cannot drift around the social name-change limits.
revoke update (full_name) on table public.account_profiles from authenticated;

create table if not exists public.social_identity_change_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.social_profiles(id) on delete cascade,
  change_type text not null check (change_type in ('display_name', 'username')),
  old_value text not null,
  new_value text not null,
  source text not null check (source in ('member', 'verified_request')),
  request_id uuid,
  changed_at timestamptz not null default now(),
  unique (user_id, request_id)
);

create index if not exists social_identity_change_events_user_type_time_idx
  on public.social_identity_change_events (user_id, change_type, changed_at desc);

alter table public.social_identity_change_events enable row level security;
alter table public.social_identity_change_events force row level security;
revoke all on table public.social_identity_change_events from public, anon, authenticated;
grant select on table public.social_identity_change_events to authenticated;

drop policy if exists social_identity_change_events_select_own on public.social_identity_change_events;
create policy social_identity_change_events_select_own
  on public.social_identity_change_events
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.social_identity_change_requests (
  id uuid primary key,
  user_id uuid not null references public.social_profiles(id) on delete cascade,
  current_name text not null,
  requested_name text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'declined', 'cancelled')),
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  review_note text,
  check (char_length(btrim(current_name)) between 1 and 80),
  check (char_length(btrim(requested_name)) between 1 and 80),
  check (review_note is null or char_length(review_note) <= 1000)
);

create unique index if not exists social_identity_change_requests_one_pending_uidx
  on public.social_identity_change_requests (user_id)
  where status = 'pending';

create index if not exists social_identity_change_requests_status_time_idx
  on public.social_identity_change_requests (status, requested_at asc);

alter table public.social_identity_change_requests enable row level security;
alter table public.social_identity_change_requests force row level security;
revoke all on table public.social_identity_change_requests from public, anon, authenticated;
grant select on table public.social_identity_change_requests to authenticated;

drop policy if exists social_identity_change_requests_select_own on public.social_identity_change_requests;
create policy social_identity_change_requests_select_own
  on public.social_identity_change_requests
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.change_social_identity(
  p_change_type text,
  p_value text,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $identity$
declare
  current_uid uuid := auth.uid();
  profile_row public.social_profiles%rowtype;
  normalized_type text := lower(btrim(coalesce(p_change_type, '')));
  normalized_value text := btrim(coalesce(p_value, ''));
  recent_count integer := 0;
  existing_request public.social_identity_change_requests%rowtype;
begin
  if current_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  if p_request_id is null then
    raise exception 'REQUEST_ID_REQUIRED' using errcode = '22023';
  end if;

  select *
  into profile_row
  from public.social_profiles
  where id = current_uid
  for update;

  if not found then
    raise exception 'PROFILE_UNAVAILABLE' using errcode = 'P0002';
  end if;

  if normalized_type = 'display_name' then
    if char_length(normalized_value) < 1 or char_length(normalized_value) > 80 then
      raise exception 'DISPLAY_NAME_INVALID' using errcode = '22023';
    end if;

    if normalized_value = profile_row.display_name then
      return jsonb_build_object(
        'status', 'unchanged',
        'change_type', 'display_name',
        'display_name', profile_row.display_name,
        'username', profile_row.username,
        'is_verified', profile_row.is_verified
      );
    end if;

    if profile_row.is_verified then
      select *
      into existing_request
      from public.social_identity_change_requests
      where id = p_request_id
        and user_id = current_uid;

      if found then
        return jsonb_build_object(
          'status', existing_request.status,
          'change_type', 'display_name',
          'request_id', existing_request.id,
          'requested_name', existing_request.requested_name,
          'is_verified', true
        );
      end if;

      if exists (
        select 1
        from public.social_identity_change_requests
        where user_id = current_uid
          and status = 'pending'
      ) then
        raise exception 'DISPLAY_NAME_REQUEST_PENDING' using errcode = 'P0001';
      end if;

      insert into public.social_identity_change_requests (
        id, user_id, current_name, requested_name
      )
      values (
        p_request_id, current_uid, profile_row.display_name, normalized_value
      );

      return jsonb_build_object(
        'status', 'pending',
        'change_type', 'display_name',
        'request_id', p_request_id,
        'requested_name', normalized_value,
        'is_verified', true
      );
    end if;

    select count(*)::integer
    into recent_count
    from public.social_identity_change_events
    where user_id = current_uid
      and change_type = 'display_name'
      and changed_at > now() - interval '14 days';

    if recent_count >= 2 then
      raise exception 'DISPLAY_NAME_CHANGE_LIMIT' using errcode = 'P0001';
    end if;

    update public.social_profiles
    set display_name = normalized_value
    where id = current_uid;

    update public.account_profiles
    set full_name = normalized_value
    where id = current_uid;

    insert into public.social_identity_change_events (
      user_id, change_type, old_value, new_value, source, request_id
    )
    values (
      current_uid, 'display_name', profile_row.display_name, normalized_value, 'member', p_request_id
    );

    return jsonb_build_object(
      'status', 'changed',
      'change_type', 'display_name',
      'display_name', normalized_value,
      'username', profile_row.username,
      'is_verified', false,
      'remaining_in_14_days', 1 - recent_count
    );
  end if;

  if normalized_type = 'username' then
    normalized_value := lower(normalized_value);

    if normalized_value !~ '^[a-z0-9][a-z0-9._]{2,29}$' then
      raise exception 'USERNAME_INVALID' using errcode = '22023';
    end if;

    if normalized_value = any (array[
      'admin','administrator','root','support','security','sautilink','cloudengine',
      'official','api','help','about','settings','login','signup','account','privacy',
      'terms','contact','waitlist'
    ]) then
      raise exception 'USERNAME_RESERVED' using errcode = '22023';
    end if;

    if normalized_value = profile_row.username then
      return jsonb_build_object(
        'status', 'unchanged',
        'change_type', 'username',
        'display_name', profile_row.display_name,
        'username', profile_row.username,
        'is_verified', profile_row.is_verified
      );
    end if;

    select count(*)::integer
    into recent_count
    from public.social_identity_change_events
    where user_id = current_uid
      and change_type = 'username'
      and changed_at > now() - interval '30 days';

    if recent_count >= 1 then
      raise exception 'USERNAME_CHANGE_LIMIT' using errcode = 'P0001';
    end if;

    begin
      update public.account_profiles
      set username = normalized_value
      where id = current_uid;
    exception
      when unique_violation then
        raise exception 'USERNAME_TAKEN' using errcode = '23505';
      when check_violation then
        raise exception 'USERNAME_INVALID' using errcode = '22023';
    end;

    insert into public.social_identity_change_events (
      user_id, change_type, old_value, new_value, source, request_id
    )
    values (
      current_uid, 'username', profile_row.username, normalized_value, 'member', p_request_id
    );

    return jsonb_build_object(
      'status', 'changed',
      'change_type', 'username',
      'display_name', profile_row.display_name,
      'username', normalized_value,
      'is_verified', profile_row.is_verified,
      'next_username_change_at', now() + interval '30 days'
    );
  end if;

  raise exception 'IDENTITY_CHANGE_TYPE_INVALID' using errcode = '22023';
end;
$identity$;

revoke all on function public.change_social_identity(text, text, uuid) from public, anon, authenticated;
grant execute on function public.change_social_identity(text, text, uuid) to authenticated;

create or replace function public.identity_change_requests_for_staff()
returns table (
  id uuid,
  user_id uuid,
  username text,
  current_name text,
  requested_name text,
  status text,
  requested_at timestamptz,
  updated_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid,
  review_note text
)
language plpgsql
security definer
set search_path = ''
stable
as $staff_list$
declare
  staff_role text := private.phase29_staff_role();
begin
  if staff_role is null then
    raise exception 'MODERATION_ACCESS_REQUIRED' using errcode = '42501';
  end if;

  return query
  select
    request.id,
    request.user_id,
    profile.username,
    request.current_name,
    request.requested_name,
    request.status,
    request.requested_at,
    request.updated_at,
    request.reviewed_at,
    request.reviewed_by,
    request.review_note
  from public.social_identity_change_requests request
  join public.social_profiles profile on profile.id = request.user_id
  order by
    case when request.status = 'pending' then 0 else 1 end,
    request.requested_at asc;
end;
$staff_list$;

revoke all on function public.identity_change_requests_for_staff() from public, anon, authenticated;
grant execute on function public.identity_change_requests_for_staff() to authenticated;

create or replace function public.review_social_identity_request(
  p_request_id uuid,
  p_decision text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $review_identity$
declare
  current_uid uuid := auth.uid();
  staff_role text := private.phase29_staff_role();
  decision text := lower(btrim(coalesce(p_decision, '')));
  note text := nullif(btrim(coalesce(p_note, '')), '');
  request_row public.social_identity_change_requests%rowtype;
  profile_row public.social_profiles%rowtype;
begin
  if current_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  if staff_role not in ('reviewer', 'senior_reviewer') then
    raise exception 'MODERATION_REVIEW_REQUIRED' using errcode = '42501';
  end if;

  if decision not in ('approved', 'declined') then
    raise exception 'IDENTITY_DECISION_INVALID' using errcode = '22023';
  end if;

  if note is not null and char_length(note) > 1000 then
    raise exception 'IDENTITY_REVIEW_NOTE_TOO_LONG' using errcode = '22023';
  end if;

  select *
  into request_row
  from public.social_identity_change_requests
  where id = p_request_id
  for update;

  if not found or request_row.status <> 'pending' then
    raise exception 'IDENTITY_REQUEST_UNAVAILABLE' using errcode = 'P0002';
  end if;

  select *
  into profile_row
  from public.social_profiles
  where id = request_row.user_id
  for update;

  if not found then
    raise exception 'PROFILE_UNAVAILABLE' using errcode = 'P0002';
  end if;

  if decision = 'approved' then
    update public.social_profiles
    set display_name = request_row.requested_name
    where id = request_row.user_id;

    update public.account_profiles
    set full_name = request_row.requested_name
    where id = request_row.user_id;

    insert into public.social_identity_change_events (
      user_id, change_type, old_value, new_value, source, request_id
    )
    values (
      request_row.user_id,
      'display_name',
      profile_row.display_name,
      request_row.requested_name,
      'verified_request',
      request_row.id
    )
    on conflict (user_id, request_id) do nothing;
  end if;

  update public.social_identity_change_requests
  set
    status = decision,
    updated_at = now(),
    reviewed_at = now(),
    reviewed_by = current_uid,
    review_note = note
  where id = request_row.id;

  return jsonb_build_object(
    'status', decision,
    'request_id', request_row.id,
    'user_id', request_row.user_id,
    'display_name', case when decision = 'approved' then request_row.requested_name else profile_row.display_name end
  );
end;
$review_identity$;

revoke all on function public.review_social_identity_request(uuid, text, text) from public, anon, authenticated;
grant execute on function public.review_social_identity_request(uuid, text, text) to authenticated;

commit;
