-- SautiLink WhatsApp inbound foundation: first-party only. No client-facing access.
-- Meta sender credentials stay in Edge Function secrets, never in these tables.
begin;
set local lock_timeout = '5s';

create table if not exists public.whatsapp_inbound_messages (
  id bigint generated by default as identity primary key,
  waba_id text not null check (waba_id ~ '^[0-9]+$'),
  phone_number_id text not null check (phone_number_id ~ '^[0-9]+$'),
  provider_message_id text not null check (char_length(provider_message_id) between 8 and 255),
  sender_wa_id text not null check (sender_wa_id ~ '^[1-9][0-9]{6,15}$'),
  message_type text not null check (
    message_type in (
      'text', 'image', 'video', 'audio', 'document', 'sticker',
      'location', 'contacts', 'interactive', 'button', 'reaction', 'unknown'
    )
  ),
  text_body text not null default '' check (char_length(text_body) <= 4096),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  constraint whatsapp_inbound_messages_unique_provider_id
    unique (phone_number_id, provider_message_id)
);

create index if not exists whatsapp_inbound_messages_inbox_idx
  on public.whatsapp_inbound_messages (phone_number_id, received_at desc);

create table if not exists public.whatsapp_message_statuses (
  id bigint generated by default as identity primary key,
  waba_id text not null check (waba_id ~ '^[0-9]+$'),
  phone_number_id text not null check (phone_number_id ~ '^[0-9]+$'),
  provider_message_id text not null check (char_length(provider_message_id) between 8 and 255),
  recipient_wa_id text not null check (recipient_wa_id ~ '^[1-9][0-9]{6,15}$'),
  delivery_status text not null check (
    delivery_status in ('sent', 'delivered', 'read', 'failed', 'deleted')
  ),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  constraint whatsapp_message_statuses_unique_event
    unique (phone_number_id, provider_message_id, delivery_status, occurred_at)
);

create index if not exists whatsapp_message_statuses_received_idx
  on public.whatsapp_message_statuses (phone_number_id, received_at desc);

alter table public.whatsapp_inbound_messages enable row level security;
alter table public.whatsapp_message_statuses enable row level security;

revoke all on table public.whatsapp_inbound_messages from public, anon, authenticated;
revoke all on table public.whatsapp_message_statuses from public, anon, authenticated;
grant select, insert, update, delete on table
  public.whatsapp_inbound_messages, public.whatsapp_message_statuses to service_role;

grant usage, select on sequence
  public.whatsapp_inbound_messages_id_seq,
  public.whatsapp_message_statuses_id_seq to service_role;

comment on table public.whatsapp_inbound_messages is
  'First-party signed WhatsApp webhook inbox. Only service_role may read/write. No raw payloads, OTP values or media binaries are stored.';
comment on table public.whatsapp_message_statuses is
  'First-party signed WhatsApp webhook delivery status events. Only service_role may read/write.';

commit;
