-- Phase 29 — Moderation, Admin & Appeals
-- Staging-first moderation operations with server-owned staff roles, private reporter identity,
-- append-only decisions, member appeals, proportionate enforcement and immutable audit.

create schema if not exists private;

create table if not exists private.moderation_staff (
  user_id uuid primary key references public.social_profiles(id) on delete cascade,
  staff_role text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint moderation_staff_role_allowed
    check (staff_role = any (array['reviewer'::text, 'senior_reviewer'::text, 'auditor'::text]))
);

comment on table private.moderation_staff is
  'Server-owned Phase 29 moderation authorization. This table is outside the Data API and has no browser table grants.';

revoke all on table private.moderation_staff from public, anon, authenticated;

create or replace function private.phase29_staff_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select staff.staff_role
  from private.moderation_staff staff
  where staff.user_id = auth.uid()
    and staff.active = true
    and staff.staff_role in ('reviewer', 'senior_reviewer', 'auditor')
  limit 1
$$;

revoke all on function private.phase29_staff_role() from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.phase29_staff_role() to authenticated;

drop view if exists public.moderation_staff_self;
create view public.moderation_staff_self
with (security_invoker = true)
as
select
  auth.uid() as user_id,
  private.phase29_staff_role() as staff_role,
  true as active
where private.phase29_staff_role() is not null;

revoke all on table public.moderation_staff_self from public, anon, authenticated;
grant select on table public.moderation_staff_self to authenticated;

alter table public.social_reports
  add column if not exists priority text not null default 'medium',
  add column if not exists assigned_to uuid references public.social_profiles(id) on delete set null,
  add column if not exists target_owner_id uuid references public.social_profiles(id) on delete set null,
  add column if not exists context_snapshot jsonb,
  add column if not exists policy_version text not null default 'safety-v1';

alter table public.social_reports
  drop constraint if exists social_reports_priority_allowed,
  add constraint social_reports_priority_allowed
    check (priority = any (array['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  drop constraint if exists social_reports_policy_version_length,
  add constraint social_reports_policy_version_length
    check (char_length(policy_version) between 1 and 64);

create index if not exists social_reports_phase29_queue_idx
  on public.social_reports (report_status, priority, created_at, id);

create index if not exists social_reports_phase29_assigned_idx
  on public.social_reports (assigned_to, report_status, created_at)
  where assigned_to is not null;

create table if not exists public.social_moderation_actions (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.social_reports(id) on delete restrict,
  target_type text not null,
  target_id text not null,
  target_owner_id uuid references public.social_profiles(id) on delete set null,
  action_type text not null,
  reason text not null,
  policy_version text not null default 'safety-v1',
  request_id uuid not null,
  created_at timestamptz not null default now(),
  constraint social_moderation_actions_request_unique unique (request_id),
  constraint social_moderation_actions_target_type_allowed
    check (target_type = any (array['profile'::text, 'post'::text, 'comment'::text, 'message'::text])),
  constraint social_moderation_actions_type_allowed
    check (action_type = any (array[
      'dismissed'::text,
      'visibility_limited'::text,
      'content_removed'::text,
      'escalated'::text,
      'appeal_upheld'::text,
      'appeal_reversed'::text
    ])),
  constraint social_moderation_actions_reason_length
    check (char_length(btrim(reason)) between 1 and 2000),
  constraint social_moderation_actions_policy_version_length
    check (char_length(policy_version) between 1 and 64)
);

create index if not exists social_moderation_actions_owner_idx
  on public.social_moderation_actions (target_owner_id, created_at desc, id desc);

create index if not exists social_moderation_actions_report_idx
  on public.social_moderation_actions (report_id, created_at desc, id desc);

create table if not exists public.social_moderation_appeals (
  id bigint generated by default as identity primary key,
  action_id bigint not null unique references public.social_moderation_actions(id) on delete restrict,
  appellant_id uuid not null references public.social_profiles(id) on delete cascade,
  reason text not null,
  appeal_status text not null default 'open',
  assigned_to uuid references public.social_profiles(id) on delete set null,
  decision_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  decided_at timestamptz,
  constraint social_moderation_appeals_reason_length
    check (char_length(btrim(reason)) between 1 and 2000),
  constraint social_moderation_appeals_status_allowed
    check (appeal_status = any (array['open'::text, 'reviewing'::text, 'upheld'::text, 'reversed'::text])),
  constraint social_moderation_appeals_decision_reason_length
    check (decision_reason is null or char_length(btrim(decision_reason)) between 1 and 2000)
);

alter table public.social_moderation_actions
  add column if not exists appeal_id bigint references public.social_moderation_appeals(id) on delete restrict;

create index if not exists social_moderation_appeals_queue_idx
  on public.social_moderation_appeals (appeal_status, created_at, id);

create table if not exists public.social_moderation_audit (
  id bigint generated by default as identity primary key,
  event_type text not null,
  report_id bigint references public.social_reports(id) on delete set null,
  action_id bigint references public.social_moderation_actions(id) on delete set null,
  appeal_id bigint references public.social_moderation_appeals(id) on delete set null,
  actor_id uuid references public.social_profiles(id) on delete set null,
  actor_role text,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint social_moderation_audit_event_length
    check (char_length(event_type) between 1 and 64),
  constraint social_moderation_audit_actor_role_allowed
    check (actor_role is null or actor_role = any (array['reviewer'::text, 'senior_reviewer'::text, 'auditor'::text]))
);

create index if not exists social_moderation_audit_created_idx
  on public.social_moderation_audit (created_at desc, id desc);

alter table public.social_moderation_actions enable row level security;
alter table public.social_moderation_actions force row level security;
alter table public.social_moderation_appeals enable row level security;
alter table public.social_moderation_appeals force row level security;
alter table public.social_moderation_audit enable row level security;
alter table public.social_moderation_audit force row level security;

revoke all on table public.social_moderation_actions from public, anon, authenticated;
revoke all on table public.social_moderation_appeals from public, anon, authenticated;
revoke all on table public.social_moderation_audit from public, anon, authenticated;

grant select, insert on table public.social_moderation_actions to authenticated;
grant select, insert on table public.social_moderation_appeals to authenticated;
grant update (appeal_status, assigned_to, decision_reason, updated_at, decided_at)
  on public.social_moderation_appeals to authenticated;
grant select on table public.social_moderation_audit to authenticated;

drop policy if exists social_moderation_actions_select_phase29 on public.social_moderation_actions;
create policy social_moderation_actions_select_phase29
  on public.social_moderation_actions
  for select
  to authenticated
  using (
    target_owner_id = (select auth.uid())
    or ((select private.phase29_staff_role()) is not null)
  );

drop policy if exists social_moderation_actions_insert_staff_phase29 on public.social_moderation_actions;
create policy social_moderation_actions_insert_staff_phase29
  on public.social_moderation_actions
  for insert
  to authenticated
  with check (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  );

drop policy if exists social_moderation_appeals_select_phase29 on public.social_moderation_appeals;
create policy social_moderation_appeals_select_phase29
  on public.social_moderation_appeals
  for select
  to authenticated
  using (
    appellant_id = (select auth.uid())
    or ((select private.phase29_staff_role()) is not null)
  );

drop policy if exists social_moderation_appeals_insert_own_phase29 on public.social_moderation_appeals;
create policy social_moderation_appeals_insert_own_phase29
  on public.social_moderation_appeals
  for insert
  to authenticated
  with check (
    appellant_id = (select auth.uid())
    and exists (
      select 1
      from public.social_moderation_actions action
      where action.id = social_moderation_appeals.action_id
        and action.target_owner_id = (select auth.uid())
        and action.action_type in ('visibility_limited', 'content_removed')
    )
  );

drop policy if exists social_moderation_appeals_update_staff_phase29 on public.social_moderation_appeals;
create policy social_moderation_appeals_update_staff_phase29
  on public.social_moderation_appeals
  for update
  to authenticated
  using (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  )
  with check (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  );

drop policy if exists social_moderation_audit_select_phase29 on public.social_moderation_audit;
create policy social_moderation_audit_select_phase29
  on public.social_moderation_audit
  for select
  to authenticated
  using (
    actor_id = (select auth.uid())
    or ((select private.phase29_staff_role()) in ('senior_reviewer', 'auditor'))
  );

-- Staff can read case rows but reporter identity is intentionally excluded from browser grants.
drop policy if exists social_reports_select_staff_phase29 on public.social_reports;
create policy social_reports_select_staff_phase29
  on public.social_reports
  for select
  to authenticated
  using (
    ((select private.phase29_staff_role()) is not null)
  );

drop policy if exists social_reports_update_staff_phase29 on public.social_reports;
create policy social_reports_update_staff_phase29
  on public.social_reports
  for update
  to authenticated
  using (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  )
  with check (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  );

revoke select, update on table public.social_reports from authenticated;
revoke insert on table public.social_reports from authenticated;
grant insert (reporter_id, target_type, target_id, reason, details)
  on public.social_reports to authenticated;
grant select (
  id, target_type, target_id, reason, details, report_status, created_at,
  status_updated_at, reviewed_at, resolved_at, moderation_note, priority,
  assigned_to, target_owner_id, context_snapshot, policy_version
) on public.social_reports to authenticated;
grant update (
  report_status, status_updated_at, reviewed_at, resolved_at,
  moderation_note, priority, assigned_to, policy_version
) on public.social_reports to authenticated;

-- Moderation state is separate from member-selected audience/status.
alter table public.social_posts
  add column if not exists moderation_state text not null default 'visible',
  add column if not exists moderated_at timestamptz;

alter table public.social_posts
  drop constraint if exists social_posts_moderation_state_allowed,
  add constraint social_posts_moderation_state_allowed
    check (moderation_state = any (array['visible'::text, 'limited'::text, 'removed'::text]));

alter table public.social_post_comments
  add column if not exists moderation_state text not null default 'visible',
  add column if not exists moderated_at timestamptz;

alter table public.social_post_comments
  drop constraint if exists social_post_comments_moderation_state_allowed,
  add constraint social_post_comments_moderation_state_allowed
    check (moderation_state = any (array['visible'::text, 'limited'::text, 'removed'::text]));

grant select (moderation_state, moderated_at) on public.social_posts to authenticated;
grant select (moderation_state, moderated_at) on public.social_post_comments to authenticated;
grant update (moderation_state, moderated_at) on public.social_posts to authenticated;
grant update (moderation_state, moderated_at) on public.social_post_comments to authenticated;

drop policy if exists social_posts_moderation_update_phase29 on public.social_posts;
create policy social_posts_moderation_update_phase29
  on public.social_posts
  for update
  to authenticated
  using (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
    and exists (
      select 1
      from public.social_reports report
      where report.target_type = 'post'
        and report.target_id = social_posts.id::text
    )
  )
  with check (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  );

drop policy if exists social_post_comments_moderation_update_phase29 on public.social_post_comments;
create policy social_post_comments_moderation_update_phase29
  on public.social_post_comments
  for update
  to authenticated
  using (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
    and exists (
      select 1
      from public.social_reports report
      where report.target_type = 'comment'
        and report.target_id = social_post_comments.id::text
    )
  )
  with check (
    ((select private.phase29_staff_role()) in ('reviewer', 'senior_reviewer'))
  );

-- Replace signed-in/public read policies so moderated content remains visible to its author/staff for notices and appeal,
-- but is suppressed from everyone else.
drop policy if exists social_posts_select_phase26_anon on public.social_posts;
drop policy if exists social_posts_select_phase29_anon on public.social_posts;
create policy social_posts_select_phase29_anon
  on public.social_posts
  for select
  to anon
  using (
    moderation_state = 'visible'
    and post_status = 'published'
    and deleted_at is null
    and visibility = 'public'
    and circle_id is null
    and exists (
      select 1 from public.social_profiles root_owner
      where root_owner.id = social_posts.audience_owner_id
        and root_owner.is_discoverable = true
    )
    and exists (
      select 1 from public.social_profiles author_profile
      where author_profile.id = social_posts.author_id
        and author_profile.is_discoverable = true
    )
  );

drop policy if exists social_posts_select_phase28_authenticated on public.social_posts;
drop policy if exists social_posts_select_phase29_authenticated on public.social_posts;
create policy social_posts_select_phase29_authenticated
  on public.social_posts
  for select
  to authenticated
  using (
    post_status = 'published'
    and deleted_at is null
    and (
      moderation_state = 'visible'
      or author_id = (select auth.uid())
      or ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'post' and report.target_id = social_posts.id::text))
    )
    and (
      (
        visibility = 'public'
        and circle_id is null
        and (
          (select auth.uid()) = audience_owner_id
          or exists (
            select 1 from public.social_profiles root_owner
            where root_owner.id = social_posts.audience_owner_id
              and root_owner.is_discoverable = true
          )
        )
        and (
          (select auth.uid()) = author_id
          or exists (
            select 1 from public.social_profiles author_profile
            where author_profile.id = social_posts.author_id
              and author_profile.is_discoverable = true
          )
          or ((select private.phase29_staff_role()) is not null)
        )
      )
      or (
        visibility = 'followers'
        and circle_id is null
        and (
          (select auth.uid()) = audience_owner_id
          or exists (
            select 1 from public.social_follows follow
            where follow.follower_id = (select auth.uid())
              and follow.followed_id = social_posts.audience_owner_id
          )
          or ((select private.phase29_staff_role()) is not null)
        )
        and (
          (select auth.uid()) = author_id
          or exists (
            select 1 from public.social_profiles author_profile
            where author_profile.id = social_posts.author_id
              and author_profile.is_discoverable = true
          )
          or ((select private.phase29_staff_role()) is not null)
        )
      )
      or (
        visibility = 'circle'
        and circle_id is not null
        and (
          exists (
            select 1 from public.social_circle_members membership
            where membership.circle_id = social_posts.circle_id
              and membership.member_id = (select auth.uid())
          )
          or ((select private.phase29_staff_role()) is not null)
        )
      )
    )
    and (
      ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'post' and report.target_id = social_posts.id::text))
      or not exists (
        select 1
        from public.social_blocks block
        where
          (block.blocker_id = (select auth.uid())
            and block.blocked_id = any (array[social_posts.author_id, social_posts.audience_owner_id]))
          or
          (block.blocked_id = (select auth.uid())
            and block.blocker_id = any (array[social_posts.author_id, social_posts.audience_owner_id]))
      )
    )
    and (
      ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'post' and report.target_id = social_posts.id::text))
      or not exists (
        select 1
        from public.social_mutes mute
        where mute.muter_id = (select auth.uid())
          and mute.muted_id = any (array[social_posts.author_id, social_posts.audience_owner_id])
      )
    )
  );

drop policy if exists social_post_comments_select_anon on public.social_post_comments;
drop policy if exists social_post_comments_select_phase29_anon on public.social_post_comments;
create policy social_post_comments_select_phase29_anon
  on public.social_post_comments
  for select
  to anon
  using (
    moderation_state = 'visible'
    and exists (select 1 from public.social_posts post where post.id = social_post_comments.post_id)
    and exists (
      select 1 from public.social_profiles profile
      where profile.id = social_post_comments.author_id
        and profile.is_discoverable = true
    )
  );

drop policy if exists social_post_comments_select_phase28_authenticated on public.social_post_comments;
drop policy if exists social_post_comments_select_phase29_authenticated on public.social_post_comments;
create policy social_post_comments_select_phase29_authenticated
  on public.social_post_comments
  for select
  to authenticated
  using (
    exists (select 1 from public.social_posts post where post.id = social_post_comments.post_id)
    and (
      moderation_state = 'visible'
      or author_id = (select auth.uid())
      or ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'comment' and report.target_id = social_post_comments.id::text))
    )
    and (
      (select auth.uid()) = author_id
      or exists (
        select 1 from public.social_profiles profile
        where profile.id = social_post_comments.author_id
          and profile.is_discoverable = true
      )
      or ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'comment' and report.target_id = social_post_comments.id::text))
    )
    and (
      ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'comment' and report.target_id = social_post_comments.id::text))
      or not exists (
        select 1 from public.social_blocks block
        where
          (block.blocker_id = (select auth.uid()) and block.blocked_id = social_post_comments.author_id)
          or
          (block.blocker_id = social_post_comments.author_id and block.blocked_id = (select auth.uid()))
      )
    )
    and (
      ((select private.phase29_staff_role()) is not null and exists (select 1 from public.social_reports report where report.target_type = 'comment' and report.target_id = social_post_comments.id::text))
      or not exists (
        select 1 from public.social_mutes mute
        where mute.muter_id = (select auth.uid())
          and mute.muted_id = social_post_comments.author_id
      )
    )
  );

-- Rebuild report validator to capture immutable review context while keeping reporter identity private.
create or replace function private.validate_social_report_insert()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  target_owner uuid;
  snapshot jsonb;
begin
  if current_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  new.reporter_id := current_uid;
  new.report_status := 'open';
  new.status_updated_at := now();
  new.reviewed_at := null;
  new.resolved_at := null;
  new.moderation_note := null;
  new.assigned_to := null;
  new.target_owner_id := null;
  new.context_snapshot := null;
  new.policy_version := 'safety-v1';
  new.priority := case
    when new.reason in ('hate', 'privacy', 'impersonation') then 'high'
    when new.reason = 'spam' then 'medium'
    else 'medium'
  end;
  new.details := nullif(btrim(coalesce(new.details, '')), '');

  if new.target_type in ('profile', 'post', 'comment')
     and new.target_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    raise exception 'REPORT_TARGET_INVALID' using errcode = '22023';
  end if;

  if new.target_type = 'message'
     and new.target_id !~ '^[0-9]{1,19}$' then
    raise exception 'REPORT_TARGET_INVALID' using errcode = '22023';
  end if;

  case new.target_type
    when 'profile' then
      select profile.id,
             jsonb_build_object(
               'type', 'profile',
               'username', profile.username,
               'display_name', profile.display_name,
               'bio', left(profile.bio, 500),
               'is_discoverable', profile.is_discoverable
             )
        into target_owner, snapshot
      from public.social_profiles profile
      where profile.id = new.target_id::uuid;
    when 'post' then
      select post.author_id,
             jsonb_build_object(
               'type', 'post',
               'author_id', post.author_id,
               'body', left(post.body, 1000),
               'visibility', post.visibility,
               'created_at', post.created_at,
               'media_count', post.media_count
             )
        into target_owner, snapshot
      from public.social_posts post
      where post.id = new.target_id::uuid;
    when 'comment' then
      select comment.author_id,
             jsonb_build_object(
               'type', 'comment',
               'author_id', comment.author_id,
               'post_id', comment.post_id,
               'body', left(comment.body, 1000),
               'created_at', comment.created_at
             )
        into target_owner, snapshot
      from public.social_post_comments comment
      where comment.id = new.target_id::uuid;
    when 'message' then
      select message.sender_id,
             jsonb_build_object(
               'type', 'message',
               'sender_id', message.sender_id,
               'conversation_id', message.conversation_id,
               'body', left(message.body, 4000),
               'sent_at', message.sent_at
             )
        into target_owner, snapshot
      from public.dm_messages message
      join public.dm_conversations conversation
        on conversation.id = message.conversation_id
      where message.id = new.target_id::bigint
        and (
          conversation.member_one_id = current_uid
          or conversation.member_two_id = current_uid
        );
    else
      raise exception 'REPORT_TARGET_NOT_LIVE' using errcode = '0A000';
  end case;

  if not found then
    raise exception 'REPORT_TARGET_UNAVAILABLE' using errcode = 'P0002';
  end if;

  if target_owner = current_uid then
    raise exception 'SELF_REPORT_NOT_ALLOWED' using errcode = '22023';
  end if;

  new.target_owner_id := target_owner;
  new.context_snapshot := snapshot;
  return new;
end;
$$;

revoke all on function private.validate_social_report_insert() from public, anon, authenticated;

create or replace function private.validate_phase29_action_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  staff_role_value text;
  report_target_type text;
  report_target_id text;
  report_target_owner uuid;
  appeal_action_id bigint;
  original_report_id bigint;
  original_target_type text;
  original_target_id text;
  original_target_owner uuid;
begin
  staff_role_value := private.phase29_staff_role();

  if staff_role_value is null or staff_role_value not in ('reviewer', 'senior_reviewer') then
    raise exception 'MODERATION_STAFF_REQUIRED' using errcode = '42501';
  end if;

  new.reason := btrim(coalesce(new.reason, ''));
  new.policy_version := nullif(btrim(coalesce(new.policy_version, '')), '');
  if new.policy_version is null then new.policy_version := 'safety-v1'; end if;
  new.created_at := now();

  if new.action_type in ('appeal_upheld', 'appeal_reversed') then
    if staff_role_value <> 'senior_reviewer' then
      raise exception 'SENIOR_REVIEW_REQUIRED' using errcode = '42501';
    end if;
    if new.appeal_id is null then
      raise exception 'APPEAL_REQUIRED' using errcode = '22023';
    end if;

    select appeal.action_id
      into appeal_action_id
    from public.social_moderation_appeals appeal
    where appeal.id = new.appeal_id
      and appeal.appeal_status in ('open', 'reviewing');

    if not found then
      raise exception 'APPEAL_UNAVAILABLE' using errcode = 'P0002';
    end if;

    select action.report_id, action.target_type, action.target_id, action.target_owner_id
      into original_report_id, original_target_type, original_target_id, original_target_owner
    from public.social_moderation_actions action
    where action.id = appeal_action_id;

    if not found then
      raise exception 'ACTION_UNAVAILABLE' using errcode = 'P0002';
    end if;

    new.report_id := original_report_id;
    new.target_type := original_target_type;
    new.target_id := original_target_id;
    new.target_owner_id := original_target_owner;
  else
    if new.appeal_id is not null then
      raise exception 'APPEAL_NOT_ALLOWED' using errcode = '22023';
    end if;

    select report.target_type, report.target_id, report.target_owner_id
      into report_target_type, report_target_id, report_target_owner
    from public.social_reports report
    where report.id = new.report_id
      and report.report_status in ('open', 'reviewing');

    if not found then
      raise exception 'REPORT_UNAVAILABLE' using errcode = 'P0002';
    end if;

    if new.action_type = 'content_removed' and staff_role_value <> 'senior_reviewer' then
      raise exception 'SENIOR_REVIEW_REQUIRED' using errcode = '42501';
    end if;

    if new.action_type in ('visibility_limited', 'content_removed')
       and report_target_type not in ('post', 'comment') then
      raise exception 'ACTION_NOT_SUPPORTED_FOR_TARGET' using errcode = '22023';
    end if;

    new.target_type := report_target_type;
    new.target_id := report_target_id;
    new.target_owner_id := report_target_owner;
  end if;

  return new;
end;
$$;

revoke all on function private.validate_phase29_action_insert() from public, anon, authenticated;

drop trigger if exists validate_phase29_action_insert on public.social_moderation_actions;
create trigger validate_phase29_action_insert
before insert on public.social_moderation_actions
for each row execute function private.validate_phase29_action_insert();

create or replace function private.validate_phase29_appeal_insert()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
begin
  if current_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.social_moderation_actions action
    where action.id = new.action_id
      and action.target_owner_id = current_uid
      and action.action_type in ('visibility_limited', 'content_removed')
  ) then
    raise exception 'APPEAL_ACTION_UNAVAILABLE' using errcode = 'P0002';
  end if;

  new.appellant_id := current_uid;
  new.reason := btrim(coalesce(new.reason, ''));
  new.appeal_status := 'open';
  new.assigned_to := null;
  new.decision_reason := null;
  new.created_at := now();
  new.updated_at := now();
  new.decided_at := null;
  return new;
end;
$$;

revoke all on function private.validate_phase29_appeal_insert() from public, anon, authenticated;

drop trigger if exists validate_phase29_appeal_insert on public.social_moderation_appeals;
create trigger validate_phase29_appeal_insert
before insert on public.social_moderation_appeals
for each row execute function private.validate_phase29_appeal_insert();

create or replace function private.validate_phase29_appeal_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  staff_role_value text;
begin
  staff_role_value := private.phase29_staff_role();

  if staff_role_value is null or staff_role_value not in ('reviewer', 'senior_reviewer') then
    raise exception 'MODERATION_STAFF_REQUIRED' using errcode = '42501';
  end if;

  if new.action_id <> old.action_id
     or new.appellant_id <> old.appellant_id
     or new.reason <> old.reason
     or new.created_at <> old.created_at then
    raise exception 'APPEAL_IMMUTABLE_FIELDS' using errcode = '22023';
  end if;

  if new.appeal_status = 'reviewing' then
    new.assigned_to := current_uid;
    new.decision_reason := null;
    new.decided_at := null;
  elsif new.appeal_status in ('upheld', 'reversed') then
    if staff_role_value <> 'senior_reviewer' then
      raise exception 'SENIOR_REVIEW_REQUIRED' using errcode = '42501';
    end if;
    if new.decision_reason is null or char_length(btrim(new.decision_reason)) < 1 then
      raise exception 'APPEAL_DECISION_REASON_REQUIRED' using errcode = '22023';
    end if;
    new.assigned_to := current_uid;
    new.decided_at := now();
  elsif new.appeal_status <> old.appeal_status then
    raise exception 'INVALID_APPEAL_TRANSITION' using errcode = '22023';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.validate_phase29_appeal_update() from public, anon, authenticated;

drop trigger if exists validate_phase29_appeal_update on public.social_moderation_appeals;
create trigger validate_phase29_appeal_update
before update on public.social_moderation_appeals
for each row execute function private.validate_phase29_appeal_update();

create or replace function private.validate_phase29_report_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  staff_role_value text;
begin
  staff_role_value := private.phase29_staff_role();

  if staff_role_value is null or staff_role_value not in ('reviewer', 'senior_reviewer') then
    raise exception 'MODERATION_STAFF_REQUIRED' using errcode = '42501';
  end if;

  if new.reporter_id <> old.reporter_id
     or new.target_type <> old.target_type
     or new.target_id <> old.target_id
     or new.reason <> old.reason
     or coalesce(new.details, '') <> coalesce(old.details, '')
     or new.created_at <> old.created_at
     or new.target_owner_id is distinct from old.target_owner_id
     or new.context_snapshot is distinct from old.context_snapshot then
    raise exception 'REPORT_IMMUTABLE_FIELDS' using errcode = '22023';
  end if;

  if new.report_status = 'reviewing' then
    if new.assigned_to is not null and new.assigned_to <> current_uid then
      raise exception 'REPORT_ASSIGNMENT_INVALID' using errcode = '42501';
    end if;
    new.reviewed_at := coalesce(old.reviewed_at, now());
    new.status_updated_at := now();
  elsif new.report_status in ('resolved', 'dismissed') then
    new.resolved_at := coalesce(new.resolved_at, now());
    new.status_updated_at := now();
  elsif new.report_status <> old.report_status then
    raise exception 'INVALID_REPORT_TRANSITION' using errcode = '22023';
  end if;

  return new;
end;
$$;

revoke all on function private.validate_phase29_report_update() from public, anon, authenticated;

drop trigger if exists validate_phase29_report_update on public.social_reports;
create trigger validate_phase29_report_update
before update on public.social_reports
for each row execute function private.validate_phase29_report_update();

create or replace function private.apply_phase29_moderation_action()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.action_type = 'dismissed' then
    update public.social_reports
    set report_status = 'dismissed',
        moderation_note = new.reason,
        policy_version = new.policy_version,
        assigned_to = auth.uid(),
        reviewed_at = coalesce(reviewed_at, now()),
        resolved_at = now(),
        status_updated_at = now()
    where id = new.report_id;
  elsif new.action_type = 'visibility_limited' then
    if new.target_type = 'post' then
      update public.social_posts
      set moderation_state = 'limited', moderated_at = now()
      where id = new.target_id::uuid;
    else
      update public.social_post_comments
      set moderation_state = 'limited', moderated_at = now()
      where id = new.target_id::uuid;
    end if;

    update public.social_reports
    set report_status = 'resolved',
        moderation_note = new.reason,
        policy_version = new.policy_version,
        assigned_to = auth.uid(),
        reviewed_at = coalesce(reviewed_at, now()),
        resolved_at = now(),
        status_updated_at = now()
    where id = new.report_id;
  elsif new.action_type = 'content_removed' then
    if new.target_type = 'post' then
      update public.social_posts
      set moderation_state = 'removed', moderated_at = now()
      where id = new.target_id::uuid;
    else
      update public.social_post_comments
      set moderation_state = 'removed', moderated_at = now()
      where id = new.target_id::uuid;
    end if;

    update public.social_reports
    set report_status = 'resolved',
        moderation_note = new.reason,
        policy_version = new.policy_version,
        assigned_to = auth.uid(),
        reviewed_at = coalesce(reviewed_at, now()),
        resolved_at = now(),
        status_updated_at = now()
    where id = new.report_id;
  elsif new.action_type = 'escalated' then
    update public.social_reports
    set report_status = 'reviewing',
        moderation_note = new.reason,
        policy_version = new.policy_version,
        priority = case when priority = 'critical' then 'critical' else 'high' end,
        assigned_to = null,
        reviewed_at = coalesce(reviewed_at, now()),
        resolved_at = null,
        status_updated_at = now()
    where id = new.report_id;
  elsif new.action_type in ('appeal_upheld', 'appeal_reversed') then
    update public.social_moderation_appeals
    set appeal_status = case when new.action_type = 'appeal_upheld' then 'upheld' else 'reversed' end,
        assigned_to = auth.uid(),
        decision_reason = new.reason,
        updated_at = now(),
        decided_at = now()
    where id = new.appeal_id;

    if new.action_type = 'appeal_reversed' and new.target_type in ('post', 'comment') then
      if new.target_type = 'post' then
        update public.social_posts
        set moderation_state = 'visible', moderated_at = now()
        where id = new.target_id::uuid;
      else
        update public.social_post_comments
        set moderation_state = 'visible', moderated_at = now()
        where id = new.target_id::uuid;
      end if;
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.apply_phase29_moderation_action() from public, anon, authenticated;

drop trigger if exists apply_phase29_moderation_action on public.social_moderation_actions;
create trigger apply_phase29_moderation_action
after insert on public.social_moderation_actions
for each row execute function private.apply_phase29_moderation_action();

create or replace function private.audit_phase29_action()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  role_name text;
begin
  role_name := private.phase29_staff_role();

  insert into public.social_moderation_audit (
    event_type, report_id, action_id, appeal_id, actor_id, actor_role, event_payload
  ) values (
    new.action_type,
    new.report_id,
    new.id,
    new.appeal_id,
    auth.uid(),
    role_name,
    jsonb_build_object(
      'target_type', new.target_type,
      'target_id', new.target_id,
      'policy_version', new.policy_version
    )
  );

  return new;
end;
$$;

revoke all on function private.audit_phase29_action() from public, anon, authenticated;

drop trigger if exists audit_phase29_action on public.social_moderation_actions;
create trigger audit_phase29_action
after insert on public.social_moderation_actions
for each row execute function private.audit_phase29_action();

create or replace function private.notify_phase29_moderation_target()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  notification_post_id uuid;
begin
  if new.target_owner_id is null
     or new.action_type not in ('visibility_limited', 'content_removed', 'appeal_upheld', 'appeal_reversed') then
    return new;
  end if;

  if new.target_type = 'post' then
    notification_post_id := new.target_id::uuid;
  elsif new.target_type = 'comment' then
    select comment.post_id
      into notification_post_id
    from public.social_post_comments comment
    where comment.id = new.target_id::uuid;
  end if;

  insert into public.social_notifications (
    recipient_id,
    actor_id,
    post_id,
    notification_type
  ) values (
    new.target_owner_id,
    null,
    notification_post_id,
    'safety'
  );

  return new;
end;
$$;

revoke all on function private.notify_phase29_moderation_target() from public, anon, authenticated;

drop trigger if exists notify_phase29_moderation_target on public.social_moderation_actions;
create trigger notify_phase29_moderation_target
after insert on public.social_moderation_actions
for each row execute function private.notify_phase29_moderation_target();

create or replace function private.audit_phase29_report_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  role_name text;
begin
  if new.report_status is not distinct from old.report_status
     and new.assigned_to is not distinct from old.assigned_to
     and new.priority is not distinct from old.priority then
    return new;
  end if;

  role_name := private.phase29_staff_role();

  insert into public.social_moderation_audit (
    event_type, report_id, actor_id, actor_role, event_payload
  ) values (
    'report_updated',
    new.id,
    auth.uid(),
    role_name,
    jsonb_build_object(
      'old_status', old.report_status,
      'new_status', new.report_status,
      'assigned_to', new.assigned_to,
      'priority', new.priority
    )
  );

  return new;
end;
$$;

revoke all on function private.audit_phase29_report_update() from public, anon, authenticated;

drop trigger if exists audit_phase29_report_update on public.social_reports;
create trigger audit_phase29_report_update
after update on public.social_reports
for each row execute function private.audit_phase29_report_update();

create or replace function private.audit_phase29_appeal_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  role_name text;
  event_name text;
begin
  role_name := private.phase29_staff_role();

  event_name := case when tg_op = 'INSERT' then 'appeal_opened' else 'appeal_updated' end;

  insert into public.social_moderation_audit (
    event_type, appeal_id, actor_id, actor_role, event_payload
  ) values (
    event_name,
    new.id,
    auth.uid(),
    role_name,
    jsonb_build_object(
      'action_id', new.action_id,
      'status', new.appeal_status,
      'assigned_to', new.assigned_to
    )
  );

  return new;
end;
$$;

revoke all on function private.audit_phase29_appeal_change() from public, anon, authenticated;

drop trigger if exists audit_phase29_appeal_insert on public.social_moderation_appeals;
create trigger audit_phase29_appeal_insert
after insert on public.social_moderation_appeals
for each row execute function private.audit_phase29_appeal_change();

drop trigger if exists audit_phase29_appeal_update on public.social_moderation_appeals;
create trigger audit_phase29_appeal_update
after update on public.social_moderation_appeals
for each row execute function private.audit_phase29_appeal_change();
