-- First-party WhatsApp support outbound ledger and server-only thread state.
-- Production migration history: 20261007040548 whatsapp_support_outbound_foundation.
begin;
set local lock_timeout = '5s';

create table if not exists public.whatsapp_outbound_messages (
  id bigint generated by default as identity primary key,
  waba_id text not null check (waba_id ~ '^[0-9]+$'),
  phone_number_id text not null check (phone_number_id ~ '^[0-9]+$'),
  recipient_wa_id text not null check (recipient_wa_id ~ '^[1-9][0-9]{6,15}$'),
  provider_message_id text null check (
    provider_message_id is null or char_length(provider_message_id) between 8 and 255
  ),
  reply_to_provider_message_id text not null check (
    char_length(reply_to_provider_message_id) between 8 and 255
  ),
  body text not null check (char_length(body) between 1 and 4096),
  request_id uuid not null unique,
  actor_user_id uuid null references auth.users(id) on delete set null,
  send_state text not null default 'pending'
    check (send_state in ('pending', 'accepted', 'failed', 'uncertain')),
  provider_http_status integer null
    check (provider_http_status is null or provider_http_status between 100 and 599),
  provider_error_code text null
    check (provider_error_code is null or char_length(provider_error_code) <= 80),
  created_at timestamptz not null default now(),
  accepted_at timestamptz null,
  failed_at timestamptz null
);

create unique index if not exists whatsapp_outbound_provider_message_unique
  on public.whatsapp_outbound_messages (phone_number_id, provider_message_id)
  where provider_message_id is not null;

create index if not exists whatsapp_outbound_thread_idx
  on public.whatsapp_outbound_messages (phone_number_id, recipient_wa_id, created_at desc, id desc);

create index if not exists whatsapp_inbound_thread_idx
  on public.whatsapp_inbound_messages (phone_number_id, sender_wa_id, occurred_at desc, id desc);

create table if not exists public.whatsapp_support_threads (
  phone_number_id text not null check (phone_number_id ~ '^[0-9]+$'),
  customer_wa_id text not null check (customer_wa_id ~ '^[1-9][0-9]{6,15}$'),
  assigned_to uuid null references auth.users(id) on delete set null,
  thread_status text not null default 'open'
    check (thread_status in ('open', 'pending', 'closed')),
  last_read_inbound_id bigint null references public.whatsapp_inbound_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (phone_number_id, customer_wa_id)
);

create index if not exists whatsapp_support_threads_assignment_idx
  on public.whatsapp_support_threads (assigned_to, thread_status, updated_at desc);

drop view if exists public.whatsapp_support_thread_summary;
create view public.whatsapp_support_thread_summary
with (security_invoker = true)
as
with customers as (
  select distinct i.phone_number_id, i.sender_wa_id as customer_wa_id
  from public.whatsapp_inbound_messages i
  union
  select distinct o.phone_number_id, o.recipient_wa_id as customer_wa_id
  from public.whatsapp_outbound_messages o
),
summaries as (
  select
    c.phone_number_id,
    c.customer_wa_id,
    inbound.id as last_inbound_id,
    inbound.occurred_at as last_inbound_at,
    inbound.text_body as last_inbound_text,
    outbound.id as last_outbound_id,
    outbound.created_at as last_outbound_at,
    outbound.body as last_outbound_text,
    outbound.send_state as last_outbound_state,
    st.assigned_to,
    coalesce(st.thread_status, 'open') as thread_status,
    st.last_read_inbound_id,
    st.updated_at as state_updated_at
  from customers c
  left join lateral (
    select i.id, i.occurred_at, i.text_body
    from public.whatsapp_inbound_messages i
    where i.phone_number_id = c.phone_number_id
      and i.sender_wa_id = c.customer_wa_id
    order by i.occurred_at desc, i.id desc
    limit 1
  ) inbound on true
  left join lateral (
    select o.id, o.created_at, o.body, o.send_state
    from public.whatsapp_outbound_messages o
    where o.phone_number_id = c.phone_number_id
      and o.recipient_wa_id = c.customer_wa_id
    order by o.created_at desc, o.id desc
    limit 1
  ) outbound on true
  left join public.whatsapp_support_threads st
    on st.phone_number_id = c.phone_number_id
   and st.customer_wa_id = c.customer_wa_id
)
select
  s.*,
  greatest(
    coalesce(s.last_inbound_at, '-infinity'::timestamptz),
    coalesce(s.last_outbound_at, '-infinity'::timestamptz)
  ) as last_activity_at,
  case
    when s.last_inbound_at is null then false
    else s.last_inbound_at >= now() - interval '24 hours'
  end as support_window_open,
  (
    select count(*)::integer
    from public.whatsapp_inbound_messages i
    where i.phone_number_id = s.phone_number_id
      and i.sender_wa_id = s.customer_wa_id
      and (s.last_read_inbound_id is null or i.id > s.last_read_inbound_id)
  ) as unread_count
from summaries s;

alter table public.whatsapp_outbound_messages enable row level security;
alter table public.whatsapp_support_threads enable row level security;

revoke all on table public.whatsapp_outbound_messages from public, anon, authenticated;
revoke all on table public.whatsapp_support_threads from public, anon, authenticated;
revoke all on table public.whatsapp_support_thread_summary from public, anon, authenticated;

grant select, insert, update, delete on table
  public.whatsapp_outbound_messages,
  public.whatsapp_support_threads
to service_role;
grant select on table public.whatsapp_support_thread_summary to service_role;

grant usage, select on sequence public.whatsapp_outbound_messages_id_seq to service_role;

comment on table public.whatsapp_outbound_messages is
  'Staff-originated first-party WhatsApp replies. Service-role only; request_id prevents duplicate sends and provider message ids link delivery webhooks.';
comment on table public.whatsapp_support_threads is
  'Server-owned assignment/read-state for first-party WhatsApp support threads. No member/browser access.';
comment on view public.whatsapp_support_thread_summary is
  'Server-only operational WhatsApp thread summary derived from inbound/outbound ledgers and support state.';

commit;
